# Generated by Django 5.2 on 2025-04-21 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('has_admin_rights', models.BooleanField(default=False)),
                ('password_never_expires', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(auto_now=True)),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='dashboard.computer')),
            ],
        ),
        migrations.CreateModel(
            name='VerificationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('user_verification', 'User Verification'), ('admin_rights', 'Admin Rights Check'), ('vpn_status', 'VPN Status Check'), ('password_expiry', 'Password Expiry Check')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('scheduled_time', models.DateTimeField()),
                ('execution_time', models.DateTimeField(blank=True, null=True)),
                ('result_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('computers', models.ManyToManyField(blank=True, related_name='verification_tasks', to='dashboard.computer')),
            ],
        ),
        migrations.CreateModel(
            name='VPNStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('is_connected', models.BooleanField(default=False)),
                ('last_connection', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(auto_now=True)),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vpn_status', to='dashboard.computer')),
            ],
        ),
    ]
